# -*- coding: utf-8 -*-
"""ML Homework 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cr9TPzQn0_V9Xk4ZE_rs-Vg0i4GzRIKF
"""

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

df = pd.read_csv('hm_hospitales_covid_structured_30d_train.csv')
df_2 = pd.read_csv('split_train_export_30d.csv')
df_3 = pd.read_csv('fixed_test.csv')

# creating a blank series 
Type_new = pd.Series([])
# running a for loop and asigning some values to series 
for i in range(len(df_3)): 
    Type_new[i]= df_3["PATIENT ID"][i]

## Drop rest of the features and extract the target values
df = df.drop(['ed_diagnosis', 'admission_datetime', 'sex', 'PATIENT ID'],axis=1)
df_3 = df_3.drop(['ed_diagnosis', 'admission_datetime', 'sex', 'PATIENT ID'],axis=1)

Y = []
target = df_2['hospital_outcome']
Y = target
df = df.fillna(df.mean())
X = df.values
x_test = df_3.values
x_train = X
y_train = Y
clf = SVC(kernel='linear')
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print(y_pred)

df = pd.DataFrame(y_pred, columns=['hospital_outcome'])
df.insert(0, "PATIENT ID", Type_new)
df.to_csv (r'107062381.csv')